settings:
  title: 'Страница статуса'
  url: 'https://status.potatoenergy.ru' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Все системы работают'
  notAllmonitorsOperational: 'Не все системы работают'
  monitorLabelOperational: 'Работает'
  monitorLabelNotOperational: 'Не работает'
  monitorLabelNoData: 'Нет данных'
  dayInHistogramNoData: 'Нет данных'
  dayInHistogramOperational: 'Все в порядке'
  dayInHistogramNotOperational: ' инцидент(ы)' # xx зарегистрированный инцидент(ы)

monitors:
  - id: potatoenergy-ru
    name: potatoenergy.ru
    url: 'https://potatoenergy.ru/'
    method: GET
    expectStatus: 200

  - id: potatoenergy-store
    name: potatoenergy.store 
    url: 'https://potatoenergy.store/'
    method: GET
    expectStatus: 200
