settings:
  title: 'Страница статуса'
  url: 'https://status.potatoenergy.ru' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Все системы работают'
  notAllmonitorsOperational: 'Не все системы работают'
  monitorLabelOperational: 'Работает'
  monitorLabelNotOperational: 'Не работает'
  monitorLabelNoData: 'Нет данных'
  dayInHistogramNoData: 'Нет данных'
  dayInHistogramOperational: 'Все в порядке'
  dayInHistogramNotOperational: ' инцидент(ы)' # xx зарегистрированный инцидент(ы)

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'Вы пишете код. Они делают все остальное.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Создан для всего, что подключено к Интернету.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: Блог Cloudflare
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200

  - id: potatoenergy-ru
    name: potatoenergy.ru
    url: 'https://potatoenergy.ru/'
    method: GET
    expectStatus: 200

  - id: potatoenergy-store
    name: potatoenergy.store 
    url: 'https://potatoenergy.store/'
    method: GET
    expectStatus: 200
